spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.178.0.11:3306/mydb
    username: root
    password: root123!

  redis:
    host: 10.178.0.10
    port: 6379
  session:
    store-type: redis

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 300
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none
        secure: true


