spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true

server:
  port: 8080

