= API 문서
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== 0. 공통 응답
=== 기본
operation::common-result[snippets='response-body,response-fields']

=== 페이지 정보 포함
operation::common-page-result[snippets='response-body,response-fields']

== 1. 회원 API

=== 회원 생성
`POST /members`

operation::member-create[snippets='http-request,request-fields,http-response,response-fields']

=== 회원 단건 조회
`GET /member/:memberId`

operation::member-get[snippets='http-request,path-parameters,http-response,response-fields-data']

=== 회원 업데이트
`PATCH /member/:memberId`

operation::member-update[snippets='http-request,request-fields,http-response,response-fields']

=== 회원 삭제
`DELETE /member/:memberId`

operation::member-duplicate-check[snippets='http-request,request-fields,http-response,response-fields']

== 2. 로그인 API

=== 로그인
`POST /login`

operation::login[snippets='http-request,request-fields,http-response,response-fields']

=== 로그아웃
`POST /logout`

operation::logout[snippets='http-request,http-response,response-fields']

== 3. 그룹 API

=== 그룹 목록 조회
`GET /groups`

operation::groups-get[snippets='http-request,request-fields,http-response,response-fields']

=== 그룹 단건 조회
`GET /group/:groupId`

operation::group-get[snippets='http-request,path-parameters,http-response,response-fields']

=== 그룹 생성
`POST /groups`

operation::group-create[snippets='http-request,request-fields,http-response,response-fields']

=== 그룹 업데이트
`POST /group/:groupId`

operation::group-update[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 그룹 삭제
`DELETE /group/:groupId`

operation::group-delete[snippets='http-request,path-parameters,http-response,response-fields']

=== 그룹 가입
`POST /group/:groupId/join`

operation::group-join[snippets='http-request,path-parameters,http-response,response-fields']

=== 그룹 탈퇴
`POST /group/:groupId/quit`

operation::group-quit[snippets='http-request,path-parameters,http-response,response-fields']

== 4. 학습 API

=== 학습 생성
`POST /studies`

operation::study-create[snippets='http-request,request-fields,http-response,response-fields']

=== 학습 목록 조회
`GET /studies`

operation::studies-get[snippets='http-request,request-fields,http-response,response-fields-data']

== 5. 학습 티켓 API

=== 학습 티켓 발급
`POST /tickets`

operation::ticket-create[snippets='http-request,request-fields,http-response,response-fields']

=== 학습 티켓 목록 조회
`GET /tickets`

operation::tickets-get[snippets='http-request,request-fields,http-response,response-fields-data']

=== 학습 티켓 단건 조회
`GET /ticket/:ticketId`

operation::ticket-get[snippets='http-request,path-parameters,http-response,response-fields-data']

=== 학습 티켓 만료
`PATCH /ticket/:ticketId`

operation::ticket-expire[snippets='http-request,path-parameters,http-response,response-fields']

== 6. 기록 API

=== 공부 기록 목록 조회
`GET /records`

operation::records-get[snippets='http-request,request-fields,http-response,response-fields']

== 7. 게시글 API

=== 게시글 목록 조회
`GET /posts`

operation::posts-get[snippets='http-request,request-fields,http-response,response-fields-data']

=== 게시글 단건 조회
`GET /post/:postId`

operation::post-get[snippets='http-request,path-parameters,http-response,response-fields-data']

=== 게시글 생성
`POST /posts`

operation::post-create[snippets='http-request,request-fields,http-response,response-fields']

=== 게시글 업데이트
`PATCH /post/:postId`

operation::post-update[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 게시글 삭제
`DELETE /post/:postId`

operation::post-delete[snippets='http-request,path-parameters,http-response,response-fields']

== 8. 댓글 API

=== 댓글 생성
`POST /comments`

operation::comment-create[snippets='http-request,request-fields,http-response,response-fields']

=== 댓글 목록 조회
`GET /comments`

operation::comments-get[snippets='http-request,request-parameters,http-response,response-fields-data']

=== 댓글 업데이트
`UPDATE /comment/:commentId`

operation::comment-update[snippets='http-request,request-fields,http-response,response-fields']

=== 댓글 삭제
`DELETE /comment/:commentId`

operation::comment-delete[snippets='http-request,path-parameters,http-response,response-fields']

== #. Enum Type

=== PostCategory

include::{snippets}/post-category/custom-response-fields-post-category.adoc[]

=== GroupCategory

include::{snippets}/group-category/custom-response-fields-group-category.adoc[]

=== OrderBy

include::{snippets}/order-by/custom-response-fields-order-by.adoc[]
