ifndef::snippets[]
:snippets: ./build/generated-snippets
endif::[]

= API 문서

== 회원 API

=== `POST /members` - 회원 생성

operation::member-create[snippets='http-request,request-fields,http-response,response-fields']

=== `GET /member/:memberId` - 회원 단건 조회

operation::member-get[snippets='http-request,path-parameters,http-response,response-fields-data']

=== `PATCH /member/:memberId` - 회원 업데이트

operation::member-update[snippets='http-request,request-fields,http-response,response-fields']

=== `DELETE /member/:memberId` - 회원 삭제

operation::member-duplicate-check[snippets='http-request,request-fields,http-response,response-fields']

== 그룹 API

=== `GET /groups` - 그룹 목록 조회

operation::groups-get[snippets='http-request,request-fields,http-response,response-fields']

=== `GET /group/:groupId` - 그룹 조회

operation::group-get[snippets='http-request,path-parameters,http-response,response-fields']

=== `POST /groups` - 그룹 생성

operation::group-create[snippets='http-request,request-fields,http-response,response-fields']

=== `POST /group/:groupId` - 그룹 업데이트

operation::group-update[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== `DELETE /group/:groupId` - 그룹 삭제

operation::group-delete[snippets='http-request,path-parameters,http-response,response-fields']

=== `POST /group/:groupId/join` - 그룹 가입

operation::group-join[snippets='http-request,path-parameters,http-response,response-fields']

=== `POST /group/:groupId/quit` - 그룹 탈퇴

operation::group-quit[snippets='http-request,path-parameters,http-response,response-fields']

== 학습 티켓 API

=== `POST /tickets` - 학습 티켓 발급

operation::ticket-create[snippets='http-request,request-fields,http-response,response-fields']

=== `GET /tickets` - 학습 티켓 목록 조회

operation::tickets-get[snippets='http-request,request-fields,http-response,response-fields-data']

=== `GET /ticket/:ticketId` - 학습 티켓 단건 조회

operation::ticket-get[snippets='http-request,path-parameters,http-response,response-fields-data']

=== `PATCH /ticket/:ticketId` - 학습 티켓 만료

operation::ticket-expire[snippets='http-request,path-parameters,http-response,response-fields']



== 기록 API

=== `GET /records` - 공부 기록 목록 조회

operation::records-get[snippets='http-request,request-fields,http-response,response-fields']

== 게시글 API

=== `GET /posts` - 게시글 목록 조회

operation::posts-get[snippets='http-request,request-fields,http-response,response-fields-data']

=== `GET /post/:postId` - 게시글 단건 조회

operation::post-get[snippets='http-request,path-parameters,http-response,response-fields-data']

=== `POST /posts` - 게시글 생성

operation::post-create[snippets='http-request,request-fields,http-response,response-fields']

=== `PATCH /post/:postId` - 게시글 업데이트

operation::post-update[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== `DELETE /post/:postId` - 게시글 삭제

operation::post-delete[snippets='http-request,path-parameters,http-response,response-fields']


== 댓글 API

=== `POST /comments` - 댓글 생성

operation::comment-create[snippets='http-request,request-fields,http-response,response-fields']

=== `GET /comments` - 댓글 목록 조회

operation::comments-get[snippets='http-request,request-parameters,http-response,response-fields-data']

=== `UPDATE /comment/:commentId` - 댓글 업데이트

operation::comment-update[snippets='http-request,request-fields,http-response,response-fields']

=== `DELETE /comment/:commentId` - 댓글 삭제

operation::comment-delete[snippets='http-request,path-parameters,http-response,response-fields']


