ifndef::snippets[]
:snippets: ./build/generated-snippets
endif::[]

= API 문서

== 그룹 API

=== `GET /groups` - 그룹 목록 조회

operation::groups-get[snippets='http-request,request-fields,http-response,response-fields']

=== `GET /group/:groupId` - 그룹 조회

operation::group-get[snippets='http-request,path-parameters,http-response,response-fields']

=== `POST /groups` - 그룹 생성

operation::group-create[snippets='http-request,request-fields,http-response,response-fields']

=== `POST /group/:groupId` - 그룹 업데이트

operation::group-update[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== `DELETE /group/:groupId` - 그룹 삭제

operation::group-delete[snippets='http-request,path-parameters,http-response,response-fields']

=== `POST /group/:groupId/join` - 그룹 가입

operation::group-join[snippets='http-request,path-parameters,http-response,response-fields']

=== `POST /group/:groupId/quit` - 그룹 탈퇴

operation::group-quit[snippets='http-request,path-parameters,http-response,response-fields']

